# Generated by Django 2.2.3 on 2019-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20191126_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
