# Generated by Django 2.2.3 on 2020-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_add',
            name='token',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user_add',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
